version: "3"
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: chapter-02
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "3000:8000"
    depends_on:
      - postgres